name: Java CI

on:
  pull_request:
    branches:
      - Feature/wrims-devops
  push:
    branches:
      - Feature/wrims-devops

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Build with Gradle
      run: |
        ./gradlew clean
        ./gradlew build

    - name: Upload jars
      uses: actions/upload-artifact@v4.0.0
      with:
        name: jars result
        path: |
          ./wrims-core/build/libs/*.jar

    - name: Find wrims plugin jar
      id: get-jar
      run: |
        JAR_NAME=$(ls ./wrims/build/libs/*.jar | head -n 1)
        echo "JAR_NAME=$JAR_NAME" >> $GITHUB_ENV

    - name: Upload wrims-plugin jar
      uses: actions/upload-artifact@v4.0.0
      with:
        name: wrims-plugin-1.0.0.0
        path: ${{ env.JAR_NAME }}